// resources/js/components/customer/CardDetailHeader.vue
<script setup lang="ts">
import { computed } from 'vue'

import { formatVenueCategoryLabel } from '@/lib/venueScanLanding'
import { venueCoverUrl } from '@/lib/venueMedia'
import type { Venue } from '@/types'

const props = defineProps<{
  venue?: Venue | null
}>()

const cover = computed(() => (props.venue ? venueCoverUrl(props.venue) : null))
const categoryLabel = computed(() => formatVenueCategoryLabel(props.venue?.category))
const subtitle = computed(() => {
  const parts = [props.venue?.address?.trim(), categoryLabel.value].filter(Boolean)
  return parts.join(' · ')
})
</script>

<template>
  <div>
    <div class="h-[200px] overflow-hidden rounded-[22px] bg-surface-muted">
      <img
        v-if="cover"
        :src="cover"
        alt=""
        class="size-full object-cover"
      >
    </div>
    <div class="pt-4 pb-0.5">
      <h1 class="text-[30px] font-extrabold leading-tight tracking-tight text-ink">
        {{ venue?.name ?? 'Loyalty card' }}
      </h1>
      <p
        v-if="subtitle"
        class="mt-1.5 text-sm font-medium text-ink-muted"
      >
        {{ subtitle }}
      </p>
    </div>
  </div>
</template>

// apps/mobile/src/components/customer/CardDetailHeader.tsx
import { Image, Text, View } from 'react-native'

import { formatVenueCategoryLabel } from '../../lib/format'
import { venueCoverUrl } from '../../lib/media'
import { withAppFont } from '../../lib/typography'
import { colors, radius, space } from '../../theme'
import type { VenueRef } from '../../types/loyalty'

interface CardDetailHeaderProps {
  venue: VenueRef | null | undefined
}

export default function CardDetailHeader({ venue }: CardDetailHeaderProps) {
  const cover = venueCoverUrl(venue ?? undefined)
  const categoryLabel = venue?.category ? formatVenueCategoryLabel(venue.category) : null

  return (
    <View>
      <View style={{ paddingHorizontal: space.screenX, paddingTop: 4 }}>
        <View
          style={{
            height: 200,
            borderRadius: radius.card,
            overflow: 'hidden',
            backgroundColor: colors.surfaceMuted,
          }}
        >
          {cover ? (
            <Image source={{ uri: cover }} style={{ width: '100%', height: '100%' }} resizeMode="cover" />
          ) : null}
        </View>
      </View>

      <View style={{ paddingHorizontal: space.screenX, paddingTop: 16, paddingBottom: 2 }}>
        <Text style={withAppFont({ fontSize: 30, fontWeight: '800', color: colors.ink, letterSpacing: -0.6 })}>
          {venue?.name ?? 'Loyalty card'}
        </Text>
        {categoryLabel || venue?.address ? (
          <Text style={withAppFont({ marginTop: 6, fontSize: 14, fontWeight: '500', color: colors.inkMuted })}>
            {[venue?.address?.trim(), categoryLabel].filter(Boolean).join(' · ')}
          </Text>
        ) : null}
      </View>
    </View>
  )
}
