// resources/js/components/customer/HomeCampaignCard.vue
<script setup lang="ts">
import { Calendar, Clock, Sparkles, Star, Zap } from '@lucide/vue'
import { computed } from 'vue'

import { campaignEndsLabel } from '@/lib/campaignEndsLabel'
import { venueCoverUrl } from '@/lib/venueMedia'
import type { HomeCampaign, Venue } from '@/types'

const props = defineProps<{
  campaign: HomeCampaign
  featured?: boolean
  venue?: Venue | null
}>()

const endsLabel = computed(() => campaignEndsLabel(props.campaign.days_left))
const cover = computed(() => venueCoverUrl(props.venue ?? { name: props.campaign.venue_name }))
const title = computed(() => props.campaign.name?.trim() || props.campaign.headline)
const isDarkCampaign = computed(() => props.featured || props.campaign.applies_now)
</script>

<template>
  <article
    v-if="isDarkCampaign"
    class="relative min-h-[176px] overflow-hidden rounded-[22px] border border-campaign-border bg-campaign shadow-md"
    :class="featured ? 'min-h-[204px]' : ''"
  >
    <div class="flex h-full gap-3 p-[18px]">
      <div class="flex min-w-0 flex-1 flex-col justify-between">
        <div>
          <span
            class="inline-flex items-center gap-1 rounded-full border border-accent px-2.5 py-1 text-[11px] font-bold text-accent"
          >
            <Star v-if="featured" class="size-3" />
            <Zap v-else class="size-3" />
            {{ featured ? 'Featured' : 'Active' }}
          </span>
          <p class="mt-3 truncate text-xs font-semibold tracking-wide text-white/65">
            {{ campaign.venue_name }}
          </p>
          <p
            class="mt-1.5 font-extrabold leading-snug tracking-tight text-primary-text"
            :class="featured ? 'text-xl' : 'text-lg'"
          >
            {{ title }}
          </p>
          <p class="mt-1.5 line-clamp-2 text-[13px] font-medium leading-[19px] text-white/75">
            {{ campaign.message }}
          </p>
        </div>
        <p
          v-if="endsLabel"
          class="mt-2.5 flex items-center gap-1.5 text-xs font-semibold text-accent"
        >
          <Clock class="size-3.5" />
          {{ endsLabel }}
        </p>
      </div>

      <div class="relative flex w-[104px] shrink-0 items-center justify-center">
        <img
          v-if="cover"
          :src="cover"
          alt=""
          class="size-[92px] rounded-2xl border border-white/15 object-cover"
        >
        <div
          v-else
          class="size-[92px] rounded-2xl border border-white/10 bg-white/5"
        />
        <div class="absolute -right-3 -top-2 grid size-[52px] place-items-center rounded-full border-2 border-accent-border bg-campaign shadow-sm">
          <span class="text-sm font-black leading-none text-accent">{{ campaign.multiplier }}×</span>
          <span class="text-[7px] font-extrabold tracking-[0.08em] text-white/70">STAMPS</span>
        </div>
      </div>
    </div>
  </article>

  <article
    v-else
    class="min-h-[176px] rounded-[22px] border border-border bg-surface p-[18px] shadow-md"
  >
    <span class="inline-flex items-center gap-1 rounded-full border border-highlight-border bg-highlight px-2.5 py-1 text-[11px] font-bold text-ink">
      <Sparkles class="size-3" />
      New
    </span>
    <p class="mt-2.5 truncate text-xs font-semibold tracking-wide text-ink-muted">
      {{ campaign.venue_name }}
    </p>
    <p class="mt-1.5 text-lg font-extrabold leading-snug tracking-tight text-ink">
      {{ title }}
    </p>
    <p class="mt-1.5 line-clamp-2 text-[13px] font-medium leading-[19px] text-ink-muted">
      {{ campaign.message }}
    </p>
    <p
      v-if="endsLabel"
      class="mt-2.5 flex items-center gap-1.5 text-xs font-semibold text-ink-muted"
    >
      <Calendar class="size-3.5 text-ink-soft" />
      {{ endsLabel }}
    </p>
  </article>
</template>

// apps/mobile/src/components/customer/HomeCampaignCard.tsx
import { Ionicons } from '@expo/vector-icons'
import { Image, Platform, Text, View } from 'react-native'
import { campaignEndsLabel } from '../../lib/campaignEndsLabel'
import { venueCoverUrl } from '../../lib/media'
import { withAppFont } from '../../lib/typography'
import { colors, radius, shadows } from '../../theme'
import type { HomeCampaign, VenueRef } from '../../types/loyalty'

interface HomeCampaignCardProps {
  campaign: HomeCampaign
  width: number
  featured: boolean
  venue?: VenueRef | null
}

function CampaignBadge({
  label,
  icon,
  backgroundColor,
  textColor,
  borderColor,
}: {
  label: string
  icon: keyof typeof Ionicons.glyphMap
  backgroundColor: string
  textColor: string
  borderColor?: string
}) {
  return (
    <View
      style={{
        alignSelf: 'flex-start',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 999,
        backgroundColor,
        borderWidth: borderColor ? 1 : 0,
        borderColor: borderColor ?? 'transparent',
      }}
    >
      <Ionicons name={icon} size={11} color={textColor} />
      <Text style={withAppFont({ fontSize: 11, fontWeight: '700', color: textColor, letterSpacing: 0.2 })}>
        {label}
      </Text>
    </View>
  )
}

function MultiplierStampBadge({ multiplier, dark }: { multiplier: number; dark?: boolean }) {
  const ring = (
    <View
      style={{
        width: 54,
        height: 54,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: dark ? 'rgba(215, 163, 93, 0.45)' : colors.accentBorder,
        backgroundColor: dark ? 'rgba(5, 13, 30, 0.92)' : colors.surface,
        alignItems: 'center',
        justifyContent: 'center',
        ...(dark && Platform.OS === 'ios' ? shadows.sm : {}),
      }}
    >
      <View
        style={{
          position: 'absolute',
          width: 44,
          height: 44,
          borderRadius: 11,
          borderWidth: 1,
          borderColor: dark ? 'rgba(215, 163, 93, 0.28)' : 'rgba(215, 163, 93, 0.4)',
        }}
      />
      <Text style={withAppFont({ fontSize: 14, fontWeight: '900', color: dark ? colors.accent : colors.accentActive, lineHeight: 16 })}>
        {multiplier}×
      </Text>
      <Text
        style={withAppFont({
          fontSize: 7,
          fontWeight: '800',
          letterSpacing: 0.8,
          color: dark ? colors.accent : colors.inkMuted,
        })}
      >
        STAMPS
      </Text>
    </View>
  )

  return ring
}

function EndsRow({ label, tone }: { label: string; tone: 'gold' | 'muted' }) {
  const textColor = tone === 'gold' ? colors.accent : colors.inkMuted
  const iconColor = tone === 'gold' ? colors.accent : colors.inkSoft

  return (
    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 10 }}>
      <Ionicons
        name={tone === 'gold' ? 'time-outline' : 'calendar-outline'}
        size={13}
        color={iconColor}
      />
      <Text style={withAppFont({ fontSize: 12, fontWeight: '600', color: textColor })}>{label}</Text>
    </View>
  )
}

export default function HomeCampaignCard({ campaign, width, featured, venue }: HomeCampaignCardProps) {
  const endsLabel = campaignEndsLabel(campaign.days_left)
  const cover = venueCoverUrl(venue ?? { name: campaign.venue_name })
  const title = campaign.name?.trim() || campaign.headline
  const description = campaign.message

  const isDarkCampaign = featured || campaign.applies_now

  if (isDarkCampaign) {
    return (
      <View
        style={{
          width,
          minHeight: featured ? 204 : 176,
          borderRadius: radius.card,
          overflow: 'hidden',
          backgroundColor: colors.campaignBg,
          borderWidth: 1,
          borderColor: colors.campaignBorder,
          ...(Platform.OS === 'ios' ? shadows.md : { elevation: 4 }),
        }}
      >
        <View style={{ flex: 1 }}>
          <View style={{ flex: 1, flexDirection: 'row', padding: 18, gap: 12 }}>
            <View style={{ flex: 1, minWidth: 0, justifyContent: 'space-between' }}>
              <View>
                <CampaignBadge
                  label={featured ? 'Featured' : 'Active'}
                  icon={featured ? 'star' : 'flash'}
                  backgroundColor="transparent"
                  textColor={colors.accent}
                  borderColor={colors.accent}
                />
                <Text
                  style={withAppFont({
                    marginTop: 12,
                    fontSize: 12,
                    fontWeight: '600',
                    color: 'rgba(255,255,255,0.65)',
                    letterSpacing: 0.3,
                  })}
                  numberOfLines={1}
                >
                  {campaign.venue_name}
                </Text>
                <Text
                  style={withAppFont({
                    marginTop: 5,
                    fontSize: featured ? 20 : 18,
                    fontWeight: '800',
                    color: colors.primaryText,
                    lineHeight: featured ? 25 : 23,
                    letterSpacing: -0.3,
                  })}
                  numberOfLines={2}
                >
                  {title}
                </Text>
                <Text
                  style={withAppFont({
                    marginTop: 5,
                    fontSize: 13,
                    fontWeight: '500',
                    lineHeight: 19,
                    color: 'rgba(255,255,255,0.75)',
                  })}
                  numberOfLines={2}
                >
                  {description}
                </Text>
              </View>
              {endsLabel ? <EndsRow label={endsLabel} tone="gold" /> : null}
            </View>

            <View style={{ width: 104, alignItems: 'center', justifyContent: 'center' }}>
              <View style={{ position: 'relative' }}>
                {cover ? (
                  <Image
                    source={{ uri: cover }}
                    style={{
                      width: 92,
                      height: 92,
                      borderRadius: 16,
                      borderWidth: 1,
                      borderColor: 'rgba(255,255,255,0.14)',
                    }}
                    resizeMode="cover"
                  />
                ) : (
                  <View
                    style={{
                      width: 92,
                      height: 92,
                      borderRadius: 16,
                      backgroundColor: 'rgba(255,255,255,0.06)',
                      borderWidth: 1,
                      borderColor: 'rgba(255,255,255,0.1)',
                    }}
                  />
                )}
                <View style={{ position: 'absolute', top: -8, right: -12 }}>
                  <MultiplierStampBadge multiplier={campaign.multiplier} dark />
                </View>
              </View>
            </View>
          </View>
        </View>
      </View>
    )
  }

  return (
    <View
      style={{
        width,
        minHeight: 176,
        borderRadius: radius.card,
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        padding: 18,
        ...(Platform.OS === 'ios' ? shadows.md : { elevation: 2 }),
      }}
    >
      <CampaignBadge
        label="New"
        icon="sparkles"
        backgroundColor={colors.lavender}
        textColor={colors.ink}
        borderColor={colors.lavenderBorder}
      />
      <Text
        style={withAppFont({
          marginTop: 11,
          fontSize: 12,
          fontWeight: '600',
          color: colors.inkMuted,
          letterSpacing: 0.2,
        })}
        numberOfLines={1}
      >
        {campaign.venue_name}
      </Text>
      <Text
        style={withAppFont({
          marginTop: 5,
          fontSize: 18,
          fontWeight: '800',
          color: colors.ink,
          lineHeight: 23,
          letterSpacing: -0.2,
        })}
        numberOfLines={2}
      >
        {title}
      </Text>
      <Text
        style={withAppFont({
          marginTop: 5,
          fontSize: 13,
          fontWeight: '500',
          lineHeight: 19,
          color: colors.inkMuted,
        })}
        numberOfLines={2}
      >
        {description}
      </Text>
      {endsLabel ? <EndsRow label={endsLabel} tone="muted" /> : null}
    </View>
  )
}
