// resources/js/components/customer/HomeRewardCarousel.vue
<script setup lang="ts">
import type { HomeRewardSlide } from '@/composables/useCustomerHome'

import HomeRewardTicketCard from '@/components/customer/HomeRewardTicketCard.vue'
import { rewardThumbUrl } from '@/lib/rewardMedia'

defineProps<{
  slides: HomeRewardSlide[]
}>()

const emit = defineEmits<{
  claimUnavailable: []
}>()
</script>

<template>
  <div class="flex gap-3 overflow-x-auto pb-1 pr-2 snap-x snap-mandatory">
    <div
      v-for="slide in slides"
      :key="slide.id"
      class="w-[min(calc((100vw-36px)*0.86),320px)] shrink-0 snap-start"
    >
      <HomeRewardTicketCard
        v-if="slide.kind === 'ready' && slide.item"
        variant="ready"
        :title="slide.item.reward.title"
        :venue="slide.item.customer.venue"
        :image-reward="slide.item.reward"
        :unlock-id="slide.item.unlock_id"
        @claim-unavailable="emit('claimUnavailable')"
      />
      <HomeRewardTicketCard
        v-else-if="slide.kind === 'next' && slide.card"
        variant="next"
        :title="slide.card.summary?.next_reward_title ?? 'Your next reward'"
        :venue="slide.card.venue"
        :image-reward="{ title: slide.card.summary?.next_reward_title ?? 'Reward', image: null, image_thumb: null }"
        :stamps-to-go="slide.card.summary?.stamps_to_next ?? null"
        :stamp-progress="{
          collected: slide.card.summary?.stamps ?? slide.card.stamps,
          target: slide.card.summary?.next_reward_stamps ?? slide.card.summary?.max_stamps ?? 10,
        }"
        :card-id="slide.card.id"
        :venue-id="slide.card.venue_id"
      />
    </div>
  </div>
</template>

// apps/mobile/src/components/customer/HomeRewardCarousel.tsx
import { memo } from 'react'
import { ScrollView, useWindowDimensions, View } from 'react-native'

import { rewardImageUrl } from '../../lib/media'
import HomeRewardTicketCard from './HomeRewardTicketCard'
import { carousel, space } from '../../theme'
import type { RewardWalletItem, WalletCard } from '../../types/loyalty'

export type HomeRewardSlide =
  | { id: string; kind: 'ready'; item: RewardWalletItem }
  | { id: string; kind: 'next'; card: WalletCard }

interface HomeRewardCarouselProps {
  slides: HomeRewardSlide[]
}

function walletCardStampProgress(card: WalletCard) {
  return {
    collected: card.summary?.stamps ?? card.stamps,
    target: card.summary?.next_reward_stamps ?? card.summary?.max_stamps ?? 1,
  }
}

const transparent = { backgroundColor: 'transparent' as const }

function HomeRewardCarousel({ slides }: HomeRewardCarouselProps) {
  const { width: screenWidth } = useWindowDimensions()

  const cardWidth = screenWidth - space.screenX * 2 - carousel.rewardCardPeek
  const snapInterval = cardWidth + carousel.rewardCardGap

  if (!slides.length) return null

  return (
    <ScrollView
      horizontal
      showsHorizontalScrollIndicator={false}
      decelerationRate="fast"
      snapToInterval={snapInterval}
      snapToAlignment="start"
      disableIntervalMomentum
      nestedScrollEnabled
      directionalLockEnabled
      scrollEventThrottle={16}
      style={transparent}
      contentContainerStyle={{
        paddingLeft: space.screenX,
        paddingRight: space.screenX,
        backgroundColor: 'transparent',
      }}
    >
      {slides.map((item, index) => (
        <View
          key={item.id}
          style={[
            transparent,
            {
              width: cardWidth,
              marginRight: index < slides.length - 1 ? carousel.rewardCardGap : 0,
            },
          ]}
        >
          {item.kind === 'ready' ? (
            <HomeRewardTicketCard
              variant="ready"
              title={item.item.reward.title}
              venue={item.item.customer.venue}
              imageUri={rewardImageUrl(item.item.reward)}
              unlockId={item.item.unlock_id}
              width={cardWidth}
            />
          ) : (
            <HomeRewardTicketCard
              variant="next"
              title={item.card.summary?.next_reward_title ?? 'Your next reward'}
              venue={item.card.venue}
              imageUri={rewardImageUrl({
                title: item.card.summary?.next_reward_title ?? 'Reward',
                image: null,
                image_thumb: null,
              })}
              stampsToGo={item.card.summary?.stamps_to_next ?? null}
              stampProgress={walletCardStampProgress(item.card)}
              cardId={item.card.id}
              venueId={item.card.venue_id}
              width={cardWidth}
            />
          )}
        </View>
      ))}
    </ScrollView>
  )
}

export default memo(HomeRewardCarousel)
