// resources/js/components/loyalty/VenueScanQuickFacts.vue
<script setup lang="ts">
import { Gift, Smartphone, Star } from '@lucide/vue'
import { computed, type Component } from 'vue'

import { buildScanLandingQuickFacts, type ScanLandingQuickFactIcon } from '@/lib/venueScanLanding'

const props = defineProps<{
  firstRewardStamps?: number | null
  milestoneCount: number
}>()

const facts = computed(() =>
  buildScanLandingQuickFacts({
    firstRewardStamps: props.firstRewardStamps,
    milestoneCount: props.milestoneCount,
  }),
)

const iconMap: Record<ScanLandingQuickFactIcon, Component> = {
  stamps: Star,
  rewards: Gift,
  join: Smartphone,
}
</script>

<template>
  <ul class="space-y-3">
    <li
      v-for="fact in facts"
      :key="fact.text"
      class="flex items-start gap-3 text-sm text-ink"
    >
      <component
        :is="iconMap[fact.icon]"
        class="mt-0.5 size-4 shrink-0 text-accent"
        aria-hidden="true"
      />
      <span class="font-medium leading-snug">{{ fact.text }}</span>
    </li>
  </ul>
</template>

// apps/mobile/src/components/customer/VenueScanQuickFacts.tsx
import { Ionicons } from '@expo/vector-icons'
import type { ComponentProps } from 'react'
import { Text, View } from 'react-native'

import { buildScanLandingQuickFacts, type ScanLandingQuickFactIcon } from '../../lib/venueScanLanding'
import { withAppFont } from '../../lib/typography'
import { colors } from '../../theme'

type IoniconName = ComponentProps<typeof Ionicons>['name']

const iconMap: Record<ScanLandingQuickFactIcon, IoniconName> = {
  stamps: 'star-outline',
  rewards: 'gift-outline',
  join: 'phone-portrait-outline',
}

interface VenueScanQuickFactsProps {
  firstRewardStamps?: number | null
  milestoneCount: number
}

export default function VenueScanQuickFacts({ firstRewardStamps, milestoneCount }: VenueScanQuickFactsProps) {
  const facts = buildScanLandingQuickFacts({ firstRewardStamps, milestoneCount })

  return (
    <View style={{ gap: 12 }}>
      {facts.map((fact) => (
        <View key={fact.text} style={{ flexDirection: 'row', alignItems: 'flex-start', gap: 10 }}>
          <Ionicons name={iconMap[fact.icon]} size={18} color={colors.accent} style={{ marginTop: 1 }} />
          <Text style={withAppFont({ flex: 1, fontSize: 14, fontWeight: '500', lineHeight: 20, color: colors.ink })}>
            {fact.text}
          </Text>
        </View>
      ))}
    </View>
  )
}
