// apps/mobile/src/components/customer/DiscoverVenueCard.tsx
import { Ionicons } from '@expo/vector-icons'
import type { ComponentProps } from 'react'
import { Image, Platform, Text, View } from 'react-native'

import type { DiscoverVenue } from '../../lib/customerData'
import { discoverVenuePill } from '../../lib/discoverVenuePill'
import { formatVenueCategoryLabel } from '../../lib/format'
import { venueCoverUrl } from '../../lib/media'
import type { WalletCard } from '../../types/loyalty'
import PressableCard from '../ui/PressableCard'
import { colors, radius, shadows } from '../../theme'
import { withAppFont } from '../../lib/typography'

type IoniconName = ComponentProps<typeof Ionicons>['name']

function categoryIcon(category: string | null | undefined): IoniconName {
  const key = (category ?? '').toLowerCase()
  if (key === 'cafe') return 'cafe-outline'
  if (key === 'restaurant') return 'restaurant-outline'
  if (key === 'bakery') return 'ice-cream-outline'
  if (key === 'bar') return 'wine-outline'
  return 'storefront-outline'
}

interface DiscoverVenueCardProps {
  venue: DiscoverVenue
  card?: WalletCard | null
  distanceLabel?: string | null
  onPress: () => void
}

const PILL_STYLES = {
  ready: {
    backgroundColor: colors.successBg,
    borderColor: colors.successBorder,
    textColor: colors.successText,
    icon: 'gift' as const,
  },
  progress: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accentBorder,
    textColor: colors.ink,
    icon: 'ticket-outline' as const,
  },
  catalog: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.discoverPillBorder,
    textColor: colors.inkMuted,
    icon: 'ribbon-outline' as const,
  },
}

export default function DiscoverVenueCard({ venue, card, distanceLabel, onPress }: DiscoverVenueCardProps) {
  const cover = venueCoverUrl(venue)
  const categoryLabel = formatVenueCategoryLabel(venue.category)
  const joined = (venue.joined_count ?? 0) > 0
  const status = discoverVenuePill(joined, venue.rewards_count, card)
  const pillStyle = PILL_STYLES[status.tone]

  return (
    <PressableCard
      onPress={onPress}
      accessibilityRole="button"
      accessibilityLabel={venue.name}
      style={{
        flexDirection: 'row',
        gap: 14,
        padding: 14,
        borderRadius: radius.card,
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.discoverCardBorder,
        ...(Platform.OS === 'ios' ? shadows.sm : { elevation: 1 }),
      }}
    >
      <View
        style={{
          width: 96,
          height: 96,
          borderRadius: 16,
          overflow: 'hidden',
          backgroundColor: colors.discoverSearchFill,
        }}
      >
        {cover ? (
          <Image source={{ uri: cover }} style={{ width: '100%', height: '100%' }} resizeMode="cover" />
        ) : null}
      </View>

      <View style={{ flex: 1, minWidth: 0 }}>
        <View style={{ flexDirection: 'row', alignItems: 'flex-start', gap: 8 }}>
          <View
            style={{
              width: 36,
              height: 36,
              borderRadius: 18,
              backgroundColor: colors.discoverCategoryFill,
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <Ionicons name={categoryIcon(venue.category)} size={17} color={colors.discoverCategoryIcon} />
          </View>
          <View style={{ flex: 1, minWidth: 0 }}>
            <Text
              style={withAppFont({ fontSize: 17, fontWeight: '800', color: colors.ink, letterSpacing: -0.2 })}
              numberOfLines={1}
            >
              {venue.name}
            </Text>
            <Text style={withAppFont({ marginTop: 2, fontSize: 13, color: colors.inkMuted })} numberOfLines={1}>
              {distanceLabel ?? categoryLabel}
            </Text>
            {distanceLabel ? (
              <Text style={withAppFont({ marginTop: 2, fontSize: 12, color: colors.inkSoft })} numberOfLines={1}>
                {categoryLabel}
              </Text>
            ) : null}
          </View>
        </View>

        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10, flexWrap: 'wrap' }}>
          {joined ? (
            <View
              style={{
                flexDirection: 'row',
                alignItems: 'center',
                gap: 4,
                backgroundColor: colors.lavender,
                borderRadius: 999,
                paddingHorizontal: 9,
                paddingVertical: 5,
              }}
            >
              <Ionicons name="checkmark-circle" size={13} color={colors.accentActive} />
              <Text style={withAppFont({ fontSize: 11, fontWeight: '700', color: colors.ink })}>Joined</Text>
            </View>
          ) : null}
          <View
            style={{
              flexDirection: 'row',
              alignItems: 'center',
              gap: 5,
              backgroundColor: pillStyle.backgroundColor,
              borderRadius: 999,
              paddingHorizontal: 10,
              paddingVertical: 5,
              borderWidth: 1,
              borderColor: pillStyle.borderColor,
              maxWidth: '100%',
            }}
          >
            <Ionicons name={pillStyle.icon} size={13} color={pillStyle.textColor} />
            <Text
              style={withAppFont({ fontSize: 12, fontWeight: '600', color: pillStyle.textColor })}
              numberOfLines={1}
            >
              {status.label}
            </Text>
          </View>
        </View>
      </View>
    </PressableCard>
  )
}

// resources/js/components/customer/DiscoverVenueCard.vue
<script setup lang="ts">
import { CheckCircle, ChevronRight, Coffee, Gift, IceCreamCone, MapPin, Ribbon, Store, Ticket, Wine } from '@lucide/vue'
import { computed } from 'vue'

import { discoverVenuePill } from '@/lib/discoverVenuePill'
import { formatVenueCategoryLabel } from '@/lib/venueScanLanding'
import { venueCoverUrl } from '@/lib/venueMedia'
import type { Customer, Venue } from '@/types'

const props = defineProps<{
  venue: Venue
  card?: Customer | null
  distanceLabel?: string | null
}>()

const emit = defineEmits<{
  press: []
}>()

const cover = computed(() => venueCoverUrl(props.venue))
const categoryLabel = computed(() => formatVenueCategoryLabel(props.venue.category) ?? 'Venue')
const joined = computed(() => (props.venue.joined_count ?? 0) > 0)
const status = computed(() => discoverVenuePill(joined.value, props.venue.rewards_count, props.card))

const pillClass = computed(() => {
  if (status.value.tone === 'ready') return 'bg-success-bg border-success-border text-success-text'
  if (status.value.tone === 'progress') return 'bg-accent-soft border-accent-border text-ink'
  return 'bg-surface-muted border-border text-ink-muted'
})

const pillIcon = computed(() => {
  if (status.value.tone === 'ready') return Gift
  if (status.value.tone === 'progress') return Ticket
  return Ribbon
})

const categoryIcon = computed(() => {
  const key = (props.venue.category ?? '').toLowerCase()
  if (key === 'cafe') return Coffee
  if (key === 'bar') return Wine
  if (key === 'bakery') return IceCreamCone
  if (key === 'restaurant') return Store
  return Store
})
</script>

<template>
  <button
    type="button"
    class="flex w-full gap-3.5 rounded-[22px] border border-border bg-surface p-3.5 text-left shadow-sm transition hover:border-accent-border"
    @click="emit('press')"
  >
    <div class="size-24 shrink-0 overflow-hidden rounded-2xl bg-surface-muted">
      <img
        v-if="cover"
        :src="cover"
        alt=""
        class="size-full object-cover"
      >
    </div>

    <div class="min-w-0 flex-1">
      <div class="flex items-start gap-2">
        <div class="grid size-9 shrink-0 place-items-center rounded-full bg-surface-muted">
          <component :is="categoryIcon" class="size-4 text-ink" />
        </div>
        <div class="min-w-0 flex-1">
          <p class="truncate text-[17px] font-extrabold text-ink">{{ venue.name }}</p>
          <p class="mt-0.5 truncate text-sm text-ink-muted">
            {{ distanceLabel ?? categoryLabel }}
          </p>
          <p
            v-if="distanceLabel"
            class="mt-0.5 truncate text-xs text-ink-soft"
          >
            {{ categoryLabel }}
          </p>
        </div>
      </div>

      <div class="mt-2.5 flex flex-wrap items-center gap-2">
        <span
          v-if="joined"
          class="inline-flex items-center gap-1 rounded-full bg-accent-soft px-2.5 py-1 text-[11px] font-bold text-ink"
        >
          <CheckCircle class="size-3.5 text-accent-active" />
          Joined
        </span>
        <span
          class="inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-[11px] font-bold"
          :class="pillClass"
        >
          <component :is="pillIcon" class="size-3" />
          {{ status.label }}
        </span>
      </div>

      <p
        v-if="venue.address"
        class="mt-2 flex items-center gap-1 truncate text-xs text-ink-soft"
      >
        <MapPin class="size-3 shrink-0" />
        {{ venue.address }}
      </p>
    </div>

    <ChevronRight class="mt-2 size-4 shrink-0 self-start text-ink-soft" />
  </button>
</template>
