// apps/mobile/src/components/customer/WalletHeroCard.tsx
import { Link } from 'expo-router'
import { Image, Text, View } from 'react-native'

import WalletMilestoneSlots from './WalletMilestoneSlots'
import PressableCard from '../ui/PressableCard'
import { formatVenueCategoryLabel } from '../../lib/format'
import { venueCoverUrl } from '../../lib/media'
import { walletMilestoneProgress } from '../../lib/walletMilestoneProgress'
import { withAppFont } from '../../lib/typography'
import { colors, walletCard } from '../../theme'
import type { WalletCard } from '../../types/loyalty'

interface WalletHeroCardProps {
  item: WalletCard
}

export default function WalletHeroCard({ item }: WalletHeroCardProps) {
  const progress = walletMilestoneProgress(item.summary, item.stamps)
  const cover = venueCoverUrl(item.venue ?? undefined)
  const categoryLabel = formatVenueCategoryLabel(item.venue?.category)

  return (
    <Link
      href={{
        pathname: '/card/[cardId]',
        params: { cardId: String(item.id), venueId: String(item.venue_id) },
      }}
      asChild
    >
      <PressableCard style={{ borderRadius: walletCard.radius }}>
        <View
          style={{
            height: walletCard.height,
            borderRadius: walletCard.radius,
            overflow: 'hidden',
            backgroundColor: colors.primary,
          }}
        >
          {cover ? (
            <Image
              source={{ uri: cover }}
              style={{ position: 'absolute', width: '100%', height: '100%' }}
              resizeMode="cover"
            />
          ) : null}
          <View
            style={{
              position: 'absolute',
              left: 0,
              right: 0,
              top: 0,
              bottom: 0,
              backgroundColor: 'rgba(5, 13, 30, 0.72)',
            }}
          />

          <View style={{ flex: 1, padding: 14, justifyContent: 'space-between' }}>
            <View>
              <Text
                style={withAppFont({
                  fontSize: 22,
                  fontWeight: '800',
                  color: colors.primaryText,
                  letterSpacing: -0.5,
                })}
                numberOfLines={1}
              >
                {item.venue?.name ?? 'Venue'}
              </Text>
              <Text
                style={withAppFont({
                  marginTop: 2,
                  fontSize: 13,
                  fontWeight: '600',
                  color: 'rgba(255,255,255,0.82)',
                })}
              >
                {categoryLabel}
              </Text>
            </View>

            <View style={{ flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' }}>
              <View style={{ flex: 1, paddingRight: 10 }}>
                <Text
                  style={withAppFont({
                    fontSize: 14,
                    fontWeight: '700',
                    color: 'rgba(255,255,255,0.9)',
                  })}
                >
                  <Text style={{ fontSize: 18, fontWeight: '800', color: colors.accent }}>{progress.current}</Text>
                  {` / ${progress.target} stamps`}
                </Text>
                <WalletMilestoneSlots filled={progress.current} milestoneStamp={progress.milestoneStamp} />
              </View>
              <View style={{ alignItems: 'flex-end', minWidth: 72, marginBottom: 8 }}>
                <Text
                  style={withAppFont({
                    fontSize: 32,
                    fontWeight: '800',
                    color: colors.accent,
                    lineHeight: 34,
                  })}
                >
                  {progress.toNext}
                </Text>
                <Text
                  style={withAppFont({
                    fontSize: 12,
                    fontWeight: '600',
                    color: 'rgba(255,255,255,0.75)',
                    textAlign: 'right',
                  })}
                >
                  {progress.toNext === 1 ? 'stamp to go' : 'stamps to go'}
                </Text>
              </View>
            </View>
          </View>
        </View>
      </PressableCard>
    </Link>
  )
}

// resources/js/components/customer/WalletHeroCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'

import WalletMilestoneSlots from '@/components/customer/WalletMilestoneSlots.vue'
import { walletMilestoneProgress } from '@/lib/walletMilestoneProgress'
import { formatVenueCategoryLabel } from '@/lib/venueScanLanding'
import { venueCoverUrl } from '@/lib/venueMedia'
import type { Customer } from '@/types'

const props = defineProps<{
  item: Customer
}>()

const router = useRouter()

const progress = computed(() => walletMilestoneProgress(props.item.summary, props.item.stamps))
const cover = computed(() => (props.item.venue ? venueCoverUrl(props.item.venue) : null))
const categoryLabel = computed(() => formatVenueCategoryLabel(props.item.venue?.category) ?? 'Venue')

function openCard() {
  router.push({
    name: 'customer-card',
    params: { cardId: String(props.item.id) },
    query: { venue_id: String(props.item.venue_id) },
  })
}
</script>

<template>
  <button
    type="button"
    class="block w-full overflow-hidden rounded-3xl text-left shadow-[0_12px_40px_-24px_rgba(5,13,30,0.25)] transition hover:scale-[1.01]"
    @click="openCard"
  >
    <div class="relative h-[168px] overflow-hidden rounded-3xl bg-primary">
      <img
        v-if="cover"
        :src="cover"
        alt=""
        class="absolute inset-0 size-full object-cover"
      >
      <div class="absolute inset-0 bg-primary/72" />

      <div class="relative flex h-full flex-col justify-between p-3.5">
        <div>
          <p class="truncate text-[22px] font-extrabold leading-tight tracking-tight text-primary-text">
            {{ item.venue?.name ?? 'Venue' }}
          </p>
          <p class="mt-0.5 text-[13px] font-semibold text-white/80">
            {{ categoryLabel }}
          </p>
        </div>

        <div class="flex items-end justify-between gap-3">
          <div class="min-w-0 flex-1 pr-2">
            <p class="text-sm font-bold text-white/90">
              <span class="text-lg font-extrabold text-accent">{{ progress.current }}</span>
              {{ ` / ${progress.target} stamps` }}
            </p>
            <WalletMilestoneSlots
              :filled="progress.current"
              :milestone-stamp="progress.milestoneStamp"
            />
          </div>
          <div class="shrink-0 text-right">
            <p class="text-[32px] font-extrabold leading-none text-accent">{{ progress.toNext }}</p>
            <p class="text-xs font-semibold text-white/75">
              {{ progress.toNext === 1 ? 'stamp to go' : 'stamps to go' }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </button>
</template>
