// apps/mobile/src/components/customer/VenueScanRewardHeroCard.tsx
import { Ionicons } from '@expo/vector-icons'
import type { ComponentProps } from 'react'
import { Image, Text, View } from 'react-native'

import { rewardImageUrl } from '../../lib/media'
import {
  exampleFilledStamps,
  formatHeroRewardLine,
  formatHeroSubtitle,
  type VenueHeroReward,
} from '../../lib/venueScanLanding'
import { withAppFont } from '../../lib/typography'
import { colors, radius, shadows, space } from '../../theme'

type IoniconName = ComponentProps<typeof Ionicons>['name']

function categoryIcon(category?: string | null): IoniconName {
  const key = (category ?? '').toLowerCase()
  if (key === 'cafe' || key === 'coffee') return 'cafe-outline'
  if (key === 'bar') return 'wine-outline'
  if (key === 'bakery') return 'ice-cream-outline'
  if (key === 'restaurant') return 'restaurant-outline'
  return 'gift-outline'
}

interface VenueScanRewardHeroCardProps {
  venueName: string
  category?: string | null
  hero?: VenueHeroReward | null
}

export default function VenueScanRewardHeroCard({ venueName, category, hero }: VenueScanRewardHeroCardProps) {
  const heroImageUri =
    hero && (hero.image_thumb || hero.image) ? rewardImageUrl(hero) ?? undefined : undefined
  const filled = hero ? exampleFilledStamps(hero.required_stamps) : 0
  const slots = hero ? Math.min(Math.max(hero.required_stamps, 1), 10) : 0
  const stampsToGo = hero ? Math.max(hero.required_stamps - filled, 0) : 0

  return (
    <View
      style={{
        borderRadius: radius.card,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.surface,
        padding: space.cardPad,
        ...(shadows.sm as object),
      }}
    >
      <View style={{ flexDirection: 'row', alignItems: 'flex-start', gap: 14 }}>
        <View
          style={{
            width: 56,
            height: 56,
            borderRadius: 16,
            borderWidth: 1,
            borderColor: colors.accentBorder,
            backgroundColor: colors.accentSoft,
            alignItems: 'center',
            justifyContent: 'center',
            overflow: 'hidden',
          }}
        >
          {heroImageUri ? (
            <Image source={{ uri: heroImageUri }} style={{ width: '100%', height: '100%' }} />
          ) : (
            <Ionicons name={categoryIcon(category)} size={24} color={colors.accent} />
          )}
        </View>

        <View style={{ flex: 1, minWidth: 0 }}>
          <Text style={withAppFont({ fontSize: 18, fontWeight: '800', color: colors.ink, lineHeight: 24 })}>
            {formatHeroRewardLine(hero, venueName)}
          </Text>
          <Text style={withAppFont({ marginTop: 6, fontSize: 13, lineHeight: 20, color: colors.inkMuted })}>
            {formatHeroSubtitle(venueName)}
          </Text>

          {hero ? (
            <View style={{ marginTop: 14 }}>
              <View style={{ flexDirection: 'row', gap: 4 }}>
                {Array.from({ length: slots }).map((_, index) => (
                  <View
                    key={index}
                    style={{
                      flex: 1,
                      height: 6,
                      borderRadius: 4,
                      backgroundColor: index < filled ? colors.progressFilled : colors.progressTrack,
                    }}
                  />
                ))}
              </View>
              <Text style={withAppFont({ marginTop: 10, fontSize: 13, fontWeight: '700', color: colors.ink })}>
                {stampsToGo === 1 ? '1 stamp to unlock' : `${stampsToGo} stamps to unlock`}
              </Text>
            </View>
          ) : null}
        </View>
      </View>
    </View>
  )
}

// resources/js/components/loyalty/VenueScanRewardHeroCard.vue
<script setup lang="ts">
import { Coffee, Croissant, Gift, UtensilsCrossed, Wine } from '@lucide/vue'
import { computed, type Component } from 'vue'

import {
  exampleFilledStamps,
  formatHeroRewardLine,
  formatHeroSubtitle,
} from '@/lib/venueScanLanding'
import type { VenueLandingPayload } from '@/lib/onboarding'
import { rewardThumbUrl } from '@/lib/rewardMedia'

const props = defineProps<{
  venueName: string
  category?: string | null
  hero: VenueLandingPayload['hero_reward']
}>()

const rewardLine = computed(() => formatHeroRewardLine(props.hero, props.venueName))
const subtitle = computed(() => formatHeroSubtitle(props.venueName))
const filledStamps = computed(() =>
  props.hero ? exampleFilledStamps(props.hero.required_stamps) : 0,
)
const progressSlots = computed(() =>
  props.hero ? Math.min(Math.max(props.hero.required_stamps, 1), 10) : 0,
)
const stampsToGo = computed(() =>
  props.hero ? Math.max(props.hero.required_stamps - filledStamps.value, 0) : 0,
)
const categoryIcon = computed<Component>(() => {
  const value = (props.category ?? '').toLowerCase()
  if (value === 'cafe' || value === 'coffee') return Coffee
  if (value === 'bar') return Wine
  if (value === 'bakery') return Croissant
  if (value === 'restaurant') return UtensilsCrossed
  return Gift
})
</script>

<template>
  <div
    class="overflow-hidden rounded-3xl border border-border bg-surface p-5 shadow-[0_12px_40px_-24px_rgba(5,13,30,0.12)]"
  >
    <div class="flex items-start gap-4">
      <div
        class="grid size-14 shrink-0 place-items-center overflow-hidden rounded-2xl border border-accent-border/30 bg-accent-soft"
      >
        <img
          v-if="hero?.image_thumb || hero?.image"
          :src="rewardThumbUrl(hero)"
          alt=""
          class="size-full object-cover"
        >
        <component
          :is="categoryIcon"
          v-else
          class="size-6 text-accent"
          aria-hidden="true"
        />
      </div>

      <div class="min-w-0 flex-1">
        <p class="text-lg font-black leading-snug text-ink">
          {{ rewardLine }}
        </p>
        <p class="mt-1.5 text-sm leading-relaxed text-ink-muted">
          {{ subtitle }}
        </p>

        <div v-if="hero" class="mt-4">
          <div class="flex gap-1">
            <span
              v-for="index in progressSlots"
              :key="index"
              class="h-1.5 flex-1 rounded-full"
              :class="index <= filledStamps ? 'bg-progress-filled' : 'bg-progress-track'"
              aria-hidden="true"
            />
          </div>
          <p class="mt-2.5 text-sm font-semibold text-ink">
            {{ stampsToGo === 1 ? '1 stamp to unlock' : `${stampsToGo} stamps to unlock` }}
          </p>
        </div>
      </div>
    </div>
  </div>
</template>
